name: Build Check

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/setup@v2
        with:
          version: ^11.0.0
          runtime: node@22
          cache: true
          install: false

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
